apiVersion: v1
kind: Service
metadata:
  name: evs-rocket-chat-prod-deployment
spec:
  selector:
    app: evs-rocket-chat-prod-deployment
  ports:
    - name: evs-rocket-chat-prod-deployment
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: evs-rocket-chat-stg-deployment
spec:
  selector:
    app: evs-rocket-chat-stg-deployment
  ports:
    - name: evs-rocket-chat-stg-deployment
      protocol: TCP
      port: 3000
      targetPort: 3000
