apiVersion: apps/v1
kind: Deployment
metadata:
  name: evs-fe-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: evs-fe-deployment
  template:
    metadata:
      labels:
        app: evs-fe-deployment
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: evs-fe-deployment

      containers:
        - name: evs-fe-deployment
          image: ghcr.io/engvision/project-engvision:frontend
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: k8s-ghcr
