apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evs-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "api.engvision.edu.vn"
        - "engvision.edu.vn"
        - "stg.engvision.edu.vn"
        - "api-stg.engvision.edu.vn"
        - "www.engvision.edu.vn"
        - "whisper.engvision.edu.vn"
        - "rocket-chat.engvision.edu.vn"
        - "rocket-chat-stg.engvision.edu.vn"
  rules:
    - host: "api.engvision.edu.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evs-be-master-service
                port:
                  number: 5000

    - host: "engvision.edu.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evs-fe-master-service
                port:
                  number: 3000

    - host: "www.engvision.edu.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evs-fe-master-service
                port:
                  number: 3000

    - host: "stg.engvision.edu.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evs-fe-develop-service
                port:
                  number: 3000

    - host: "api-stg.engvision.edu.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evs-be-develop-service
                port:
                  number: 5000

    - host: "whisper.engvision.edu.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evs-whisper-deployment
                port:
                  number: 8000

    - host: "rocket-chat.engvision.edu.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evs-rocket-chat-prod-deployment
                port:
                  number: 3000

    - host: "rocket-chat-stg.engvision.edu.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evs-rocket-chat-stg-deployment
                port:
                  number: 3000
