- hosts: localhost
  gather_facts: no
  tasks:
    - name: Install NGINX Ingress Controller
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition: "{{ lookup('url', 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/do/deploy.yaml', split_lines=False) }}"

    - name: Add Jetstack Helm repository
      kubernetes.core.helm_repository:
        repo_name: jetstack
        repo_url: https://charts.jetstack.io
        state: present

    - name: Install Cert-Manager
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig }}"
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        values:
          installCRDs: true

    - name: Add Prometheus Helm repository
      kubernetes.core.helm_repository:
        repo_name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
        state: present

    - name: Install Prometheus
      community.kubernetes.helm:
        kubeconfig: "{{ kubeconfig }}"
        name: prometheus
        chart_ref: prometheus-community/prometheus
        release_namespace: monitoring
        create_namespace: true

    - name: Add Grafana Helm repository
      kubernetes.core.helm_repository:
        repo_name: grafana
        repo_url: https://grafana.github.io/helm-charts
        state: present

    - name: Install Grafana
      community.kubernetes.helm:
        kubeconfig: "{{ kubeconfig }}"
        name: grafana
        chart_ref: grafana/grafana
        release_namespace: monitoring
        create_namespace: true

    - name: Add Argo CD Helm repository
      kubernetes.core.helm_repository:
        repo_name: argo
        repo_url: https://argoproj.github.io/argo-helm
        state: present

    - name: Install Argo CD
      community.kubernetes.helm:
        kubeconfig: "{{ kubeconfig }}"
        name: argo-cd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
